### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora-ga
lora_target: all
lora_rank: 64
lora_alpha: 16

### dataset
dataset_dir: train/LLaMA-Factory/data
dataset: Open-Thoughts-2k-10k
template: qwen25
cutoff_len: 20000
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
### output
output_dir: saves/Open-Thoughts-2k-10k/Qwen2.5-7B-Instruct/lora-ga-64
logging_steps: 1
save_steps: 200
plot_loss: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

report_to: wandb
run_name: Open-Thoughts-2k-10k/Qwen2.5-7B-Instruct/lora-ga-64

