### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 128
flash_attn: fa2

### dataset
dataset_dir: train/LLaMA-Factory/data
dataset: math-code-short-cot-40k
template: qwen25
cutoff_len: 16384
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
### output
output_dir: qwen2-7b_lora_sft_math_code_short_cot_40k-128
logging_steps: 1
save_steps: 200
plot_loss: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 12
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000


report_to: wandb
run_name: qwen2-7b_lora_sft_math_code_short_cot_40k-128

