### model
model_name_or_path: /cpfs01/data/shared/Group-m6/fangyu.lfy/hf_models/Qwen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 256
flash_attn: fa2

### dataset
dataset_dir: train/LLaMA-Factory/data
dataset: math-long-cot-80k
template: qwen25
cutoff_len: 16384
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
### output
output_dir: qwen2-7b_lora_sft_math_long_cot_80k-256
logging_steps: 1
save_steps: 200
plot_loss: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 12
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000


report_to: wandb
run_name: qwen2-7b_lora_sft_math_long_cot_80k-256

