### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 64
flash_attn: fa2
additional_target: R,W,scale
shift_gate: true

### dataset
dataset_dir: train/LLaMA-Factory/data
dataset: Open-Thoughts-2k-10k
template: qwen25
cutoff_len: 20000
max_samples: 20
overwrite_cache: False
preprocessing_num_workers: 16
### output
output_dir: saves/debug
logging_steps: 1
save_steps: 10
plot_loss: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

resume_from_checkpoint: False